server {
    listen 25222 ssl;
    server_name localhost;

    ssl_certificate     /home/vweber/dev/.certs/localhost.pem;
    ssl_certificate_key /home/vweber/dev/.certs/localhost.key.pem;

    root /home/vweber/dev/elden-ring-progression-tracker;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

