server {
    listen 25222;
    server_name localhost;

    root REPLACE_THIS_WITH_THE_NAME_OF_THE_FOLDER_WITH_THIS_FILE;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}